#! /usr/bin/env bash
function tostatus {
    status="$(eval "$@")"
    return "$status"
}
exec 3>&1
"${@:2}" 2>&1 >&3 | grep -v "$1" | tee /dev/fd/2 | tostatus "head -c1 | wc -c"
exit $((PIPESTATUS[0]*PIPESTATUS[3]))
